### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by SavPhill** [patchstack/documentation#5]
On this page: https://docs.patchstack.com/faq-troubleshooting/firewall/how-do-i-use-the-country-blocking-feature/

If you click on the hyperlink shown in the word 'here' it points to https://docs.patchstack.com/patchstack-app/site-dashboard/protection/site-protection-additional-settings/#country-blocking

This shows a 404 and the link appears to be broken

**Comment by palmiak** [comment]
Thanks - fixed :)
